import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "fi";

const translations = {
  en: {
    // Nav / Index
    signIn: "Sign In",
    signOut: "Sign Out",
    getStarted: "Get Started",
    heroChip: "Digital menus for modern restaurants",
    heroTitle: "Your menu, one scan away",
    heroDesc: "Create beautiful digital menus with NFC and QR codes. Show allergens, calories, and dietary info. Update in real time.",
    startFree: "Start for free",
    viewDemo: "View live demo",
    featureQr: "QR & NFC Ready",
    featureQrDesc: "Customers scan to view your menu instantly on their phone.",
    featureMobile: "Mobile First",
    featureMobileDesc: "Beautiful, fast menus designed for every screen size.",
    featureRealtime: "Real-Time Updates",
    featureRealtimeDesc: "Change prices, items, or availability — reflected instantly.",
    footerText: "Digital menus made simple.",

    // Why Tapli page
    whyNav: "Why Tapli",
    whyTitle: "Why restaurants choose Tapli",
    whySubtitle: "Everything your guests need — one scan away.",
    why1Title: "QR & NFC ready",
    why1Desc: "Guests scan a QR code or tap an NFC tag to open your menu instantly on their phone — no app download, no account needed. Place a QR code on the table, at the entrance, or on a business card. With NFC, a single tap on a sticker or card is all it takes. Fast, frictionless, and works on every modern smartphone.",
    why2Title: "Update in real time",
    why2Desc: "Ran out of the daily special? Raising prices next week? Just log in, make the change, and it's live immediately — for every guest, on every table, at the same time. No trips to the printer, no reprinting costs, no outdated paper menus handed to guests. Your menu is always exactly as it should be.",
    why3Title: "Allergen & dietary filters",
    why3Desc: "Guests can filter the menu by allergens, calories, protein, and dietary preferences like vegan, halal, or gluten-free before they even order. This means fewer interruptions for your staff, faster ordering, and a better experience for guests with dietary needs. It also helps you stay compliant with EU allergen labelling requirements.",
    why4Title: "No printing costs",
    why4Desc: "A typical restaurant reprints menus several times a year — every price change, every seasonal update, every new dish costs time and money. With Tapli, there are no design fees, no print runs, and no waste. One digital menu that you control entirely, updated in seconds, for a simple flat monthly fee.",

    // Auth
    signInDesc: "Sign in to manage your menu",
    createAccount: "Create your restaurant account",
    verifyDesc: "Enter the verification code sent to your email",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm password",
    firstName: "First name",
    lastName: "Last name",
    restaurantName: "Restaurant name",
    yourPosition: "Your position at the restaurant",
    enterPosition: "Enter your position",
    signingIn: "Signing in...",
    creatingAccount: "Creating account...",
    verifying: "Verifying...",
    verifyEmail: "Verify Email",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    signUp: "Sign up",
    didntReceive: "Didn't receive the code?",
    goBack: "Go back",
    verificationSent: "Verification code sent!",
    checkEmail: "Check your email for the 6-digit code.",
    passwordsDontMatch: "Passwords don't match",
    passwordsMatchDesc: "Please make sure both passwords are identical.",
    weakPassword: "Weak password",
    weakPasswordDesc: "Must be 8+ characters with uppercase, lowercase, number, and special character.",
    verificationFailed: "Verification failed",
    error: "Error",
    errorLoadingMenu: "Error loading menu",
    uploadError: "Upload error",

    // Dashboard — restaurant info
    restaurantInfo: "Restaurant Info",
    editName: "Restaurant Name",
    sloganLabel: "Slogan / Tagline",
    sloganPlaceholder: "e.g. Farm-to-table Nordic cuisine",
    descriptionLabel: "About (short description)",
    descriptionPlaceholder: "A short sentence about your restaurant",
    openingHoursLabel: "Opening Hours",
    daysPlaceholder: "e.g. Mon–Fri",
    hoursPlaceholder: "e.g. 11:00–22:00",
    addRow: "Add row",
    saveChanges: "Save Changes",
    saved: "Saved",
    changesSaved: "Restaurant info updated.",
    qrCode: "QR Code",
    qrCodeDesc: "Customers scan this to open your menu.",
    downloadQr: "Download PNG",
    copyLink: "Copy link",
    linkCopied: "Copied!",
    filterSliders: "Customer Filter Sliders",
    filterSlidersDesc: "Set the min/max range customers can slide to. Toggle off to hide a slider entirely.",
    sliderCalories: "Calories (kcal)",
    sliderProtein: "Protein (g)",
    sliderBudget: "Budget (€)",
    sliderMin: "Min",
    sliderMax: "Max",
    sliderEnabled: "Show slider",

    // Dashboard
    viewMenu: "View menu →",
    setupTitle: "Set up your restaurant",
    setupDesc: "Give your restaurant a name to get started with your digital menu.",
    menuAvailableAt: "Your menu will be available at:",
    creating: "Creating...",
    createRestaurant: "Create Restaurant",
    restaurantBranding: "Restaurant Branding",
    logo: "Logo",
    logoRecommended: "Recommended: 400 × 400 px · Square",
    logoFormats: "PNG, JPG or HEIC",
    logoMaxSize: "Max 2 MB",
    logoSizeError: "Logo must be under 2 MB.",
    coverPhoto: "Cover Photo",
    uploadCover: "Click to upload a cover photo",
    changeCover: "Change cover photo",
    coverRecommended: "Recommended: 1200 × 400 px",
    coverFormats: "PNG, JPG or HEIC · Max 5 MB",
    coverMaxSize: "Max 5 MB",
    coverSizeError: "Cover photo must be under 5 MB.",
    pasteHint: "Paste image (⌘V)",
    bannerBlur: "Banner blur",
    bannerBlurDesc: "Blur the cover photo so your restaurant name stays readable.",
    categories: "Categories",
    newCategory: "New category",
    menuItems: "Menu Items",
    addItem: "Add Item",
    editItem: "Edit Item",
    addMenuItem: "Add Menu Item",
    noItemsYet: "No menu items yet. Add your first item!",
    uncategorized: "Uncategorized",
    loadingMenu: "Loading menu...",

    // Menu Item Form
    name: "Name",
    description: "Description",
    price: "Price",
    category: "Category",
    selectCategory: "Select category",
    calories: "Calories",
    proteinG: "Protein (g)",
    photo: "Photo",
    currentPhoto: "Current photo",
    changePhoto: "Change photo",
    removePhoto: "Remove photo",
    photoWillBeRemoved: "Photo will be removed on save.",
    undo: "Undo",
    allergens: "Allergens",
    dietaryTags: "Dietary Tags",
    available: "Available",
    availability: "Availability",
    alwaysAvailable: "Always available",
    timeBased: "Time-based",
    availableAt: "Available at",
    addSlot: "Add time slot",
    slotFrom: "From",
    slotTo: "To",
    presetBreakfast: "Breakfast",
    presetLunch: "Lunch",
    presetDinner: "Dinner",
    notAvailableNow: "Not available right now",
    saving: "Saving...",
    update: "Update",
    cancel: "Cancel",

    // Customer menu
    menuNotFound: "Menu not found",
    restaurantNotExist: "This restaurant doesn't exist.",
    noMatchFilters: "No items match your filters.",
    noMenuItems: "No menu items yet.",
    discoverMore: "Explore other menus on Tapli",
    filters: "Filters",
    clear: "Clear",
    excludeAllergens: "Exclude allergens",
    dietaryPreference: "Dietary preference",
    caloriesRange: "Calories",
    kcal: "kcal",
    protein: "protein",

    // Food style chips
    highProtein: "High Protein",
    highCarb: "High Carb",
    highFatKeto: "High Fat / Keto",
    lowCalorie: "Low Calorie",
    highEnergy: "High Energy",
    plantBased: "Plant Based",

    // Roles
    owner: "Owner",
    generalManager: "General Manager",
    headChef: "Head Chef",
    sousChef: "Sous Chef",
    floorManager: "Floor Manager",
    marketingManager: "Marketing Manager",
    operationsManager: "Operations Manager",
    other: "Other",

    // Pricing & Upgrade
    pricing: "Pricing",
    pricingTitle: "Simple, transparent pricing",
    pricingSubtitle: "Choose the plan that fits your restaurant. Switch or cancel anytime.",
    freeTrialNote: "All plans include a 14-day free trial. No credit card required.",
    planMonthly: "Monthly",
    planQuarterly: "Quarterly",
    planAnnual: "Annual",
    perMonth: "/month",
    billedMonthly: "Billed monthly",
    billedQuarterly: "Billed €87 every 3 months",
    billedAnnually: "Billed €300 per year",
    save17: "Save 17%",
    save29: "Save 29%",
    mostPopular: "Most Popular",
    startFreeTrial: "Start Free Trial",
    subscribeNow: "Subscribe Now",
    upgradeTitle: "Upgrade your plan",
    upgradeSubtitle: "Pick a plan to keep using Tapli without interruption.",
    // Monthly features
    feat1Menu: "1 menu",
    feat50Items: "Up to 50 menu items",
    featQrNfc: "QR & NFC support",
    featAllergenInfo: "Allergen & dietary info",
    featPhotoUploads: "Photo uploads",
    featBilingual: "Finnish & English support",
    featRealtimeUpdates: "Real-time updates",
    featCustomColours: "Custom menu colours",
    // Quarterly extra features
    feat3Menus: "Up to 3 menus",
    featUnlimitedItems: "Unlimited menu items",
    featItemBadges: "Menu item badges (New, Chef's Pick)",
    featAnalytics: "Analytics & view counts",
    featPdfExport: "PDF menu export",
    featPrioritySupport: "Priority support",
    // Annual extra features
    featExtraLanguages: "Extra languages (Swedish, Estonian, Russian)",
    featUnlimitedMenus: "Unlimited menus",
    featTimedMenus: "Time-based menus (lunch/dinner)",
    featCustomQr: "Custom QR code with restaurant logo",
    featOnboarding: "Onboarding call",
    featAccountManager: "Dedicated account manager",

    // Contact page
    contact: "Contact Us",
    contactTitle: "Get in touch",
    contactSubtitle: "Have a question or want to work with us? Reach out anytime.",
    contactEmail: "Email us",
    contactFollowUs: "Follow us",

    // 404 page
    pageNotFound: "Page not found",
    pageNotFoundDesc: "Oops! The page you're looking for doesn't exist.",
    returnHome: "Return to Home",

    // Accessibility alt text
    logoAlt: "Restaurant logo",
    coverAlt: "Restaurant cover photo",

    // Category name translations (English DB names → display name)
    catOffers: "Offers",
    catAppetizers: "Appetizers",
    catSaladSoup: "Salad & Soup",
    catPastaRisotto: "Pasta & Risotto",
    catPizzaLasagne: "Pizza & Lasagne",
    catForKids: "For Kids",
    catVegan: "Vegan",
    catDesserts: "Desserts",
    catDrinks: "Drinks",
    catAlcohol: "Alcohol",
    catStarters: "Starters",
    catMainCourses: "Main Courses",
    catSideDishes: "Side Dishes",
    catAlcoholicDrinks: "Alcoholic Drinks",
    catNonAlcoholicDrinks: "Non-Alcoholic Drinks",

    // Menu item form section headers
    freeFrom: "Free From",
    dietaryAndLifestyle: "Dietary & Lifestyle",
    optional: "optional",
    englishTranslation: "English translation",
    translateToEn: "Translate to English",
    translateToFi: "Translate to Finnish",
    translating: "Translating…",
    translateError: "Translation failed",

    // Free From allergen tags (item is free from this allergen)
    tagGlutenFree: "Gluten-free",
    tagDairyFree: "Dairy-free",
    tagEggFree: "Egg-free",
    tagFishFree: "Fish-free",
    tagPeanutFree: "Peanut-free",
    tagNutFree: "Nut-free",
    tagSoyFree: "Soy-free",
    tagShellfishFree: "Shellfish-free",
    tagSesameFree: "Sesame-free",
    tagCeleryFree: "Celery-free",
    tagMustardFree: "Mustard-free",
    tagSulphiteFree: "Sulphite-free",
    tagLupinFree: "Lupin-free",
    tagMolluscrFree: "Mollusc-free",

    // Dietary & lifestyle tags
    tagVegan: "Vegan",
    tagVegetarian: "Vegetarian",
    tagLactoseFree: "Lactose-free",
    tagPlantBased: "Plant-based",
    tagLowCarb: "Low-carb",
    tagKeto: "Keto",
    tagHighProtein: "High-protein",
    tagNoAddedSugar: "No added sugar",
    tagLowCalorie: "Low-calorie",
    tagHalal: "Halal",
    tagKosher: "Kosher",
    tagNoPork: "No pork",
    tagNoAlcohol: "No alcohol",
    tagNoBeef: "No beef",
  },
  fi: {
    // Nav / Index
    signIn: "Kirjaudu",
    signOut: "Kirjaudu ulos",
    getStarted: "Aloita",
    heroChip: "Digitaaliset ruokalistat moderneille ravintoloille",
    heroTitle: "Ruokalistasi, yhden skannauksen päässä",
    heroDesc: "Luo kauniita digitaalisia ruokalistoja NFC- ja QR-koodeilla. Näytä allergeenit, kalorit ja ruokavaliotiedot. Päivitä reaaliajassa.",
    startFree: "Aloita ilmaiseksi",
    viewDemo: "Katso esimerkki",
    featureQr: "QR & NFC -valmis",
    featureQrDesc: "Asiakkaat skannaavat nähdäkseen ruokalistasi heti puhelimellaan.",
    featureMobile: "Mobiili ensin",
    featureMobileDesc: "Kauniit, nopeat ruokalistat jokaiselle näytölle.",
    featureRealtime: "Reaaliaikaiset päivitykset",
    featureRealtimeDesc: "Muuta hintoja, tuotteita tai saatavuutta — näkyy heti.",
    footerText: "Digitaaliset ruokalistat yksinkertaisesti.",

    // Why Tapli page
    whyNav: "Miksi Tapli",
    whyTitle: "Miksi ravintolat valitsevat Taplin",
    whySubtitle: "Kaikki mitä vieraat tarvitsevat — yhdellä skannauksella.",
    why1Title: "QR & NFC -valmis",
    why1Desc: "Vieraat skannaavat QR-koodin tai napauttavat NFC-tagia avatakseen ruokalistan heti puhelimellaan — ei sovellusta, ei rekisteröitymistä. Sijoita QR-koodi pöydälle, sisäänkäynnille tai käyntikorttiin. NFC:llä pelkkä napautus tarraan tai korttiin riittää. Nopea, vaivaton ja toimii kaikissa moderneissa älypuhelimissa.",
    why2Title: "Reaaliaikaiset päivitykset",
    why2Desc: "Loppuiko päivän erikoisannos? Muuttuuko hinnat ensi viikolla? Kirjaudu sisään, tee muutos ja se näkyy heti — jokaiselle vieraalle, jokaisella pöydällä, samaan aikaan. Ei käyntejä tulostimelle, ei tulostuskuluja, ei vanhentuneita paperisia ruokalistoja vieraille. Ruokalistas on aina juuri sellainen kuin sen pitäisi olla.",
    why3Title: "Allergeeni- ja ruokavaliosuodattimet",
    why3Desc: "Vieraat voivat suodattaa ruokalistan allergeenien, kalorien, proteiinin ja ruokavalioiden — kuten vegaani, halal tai gluteeniton — mukaan jo ennen tilaamista. Tämä tarkoittaa vähemmän keskeytyksiä henkilökunnalle, nopeampaa tilaamista ja parempaa kokemusta erityisruokavalioita noudattaville vieraille. Se auttaa myös täyttämään EU:n allergeenimerkintävaatimukset.",
    why4Title: "Ei tulostuskuluja",
    why4Desc: "Tyypillinen ravintola tulostaa ruokalistoja useita kertoja vuodessa — jokainen hinnanmuutos, sesonkipäivitys tai uusi annos maksaa aikaa ja rahaa. Taplin kanssa ei ole suunnittelukuluja, painatustilauksia eikä hävikkiä. Yksi digitaalinen ruokalista, jota hallitset täysin, päivitetään sekunneissa kiinteällä kuukausimaksulla.",

    // Auth
    signInDesc: "Kirjaudu hallitaksesi ruokalistaasi",
    createAccount: "Luo ravintolasi tili",
    verifyDesc: "Syötä sähköpostiisi lähetetty vahvistuskoodi",
    email: "Sähköposti",
    password: "Salasana",
    confirmPassword: "Vahvista salasana",
    firstName: "Etunimi",
    lastName: "Sukunimi",
    restaurantName: "Ravintolan nimi",
    yourPosition: "Asemasi ravintolassa",
    enterPosition: "Syötä asemasi",
    signingIn: "Kirjaudutaan...",
    creatingAccount: "Luodaan tiliä...",
    verifying: "Vahvistetaan...",
    verifyEmail: "Vahvista sähköposti",
    noAccount: "Eikö sinulla ole tiliä?",
    haveAccount: "Onko sinulla jo tili?",
    signUp: "Rekisteröidy",
    didntReceive: "Etkö saanut koodia?",
    goBack: "Palaa takaisin",
    verificationSent: "Vahvistuskoodi lähetetty!",
    checkEmail: "Tarkista sähköpostisi 6-numeroinen koodi.",
    passwordsDontMatch: "Salasanat eivät täsmää",
    passwordsMatchDesc: "Varmista, että molemmat salasanat ovat samat.",
    weakPassword: "Heikko salasana",
    weakPasswordDesc: "Vähintään 8 merkkiä: iso kirjain, pieni kirjain, numero ja erikoismerkki.",
    verificationFailed: "Vahvistus epäonnistui",
    error: "Virhe",
    errorLoadingMenu: "Virhe ruokalistan lataamisessa",
    uploadError: "Latausvirhe",

    // Dashboard — restaurant info
    restaurantInfo: "Ravintolan tiedot",
    editName: "Ravintolan nimi",
    sloganLabel: "Iskulause / Tunnuslause",
    sloganPlaceholder: "esim. Pohjoismaista keittiötä pellolta pöytään",
    descriptionLabel: "Esittely (lyhyt kuvaus)",
    descriptionPlaceholder: "Lyhyt lause ravintolastasi",
    openingHoursLabel: "Aukioloajat",
    daysPlaceholder: "esim. Ma–Pe",
    hoursPlaceholder: "esim. 11:00–22:00",
    addRow: "Lisää rivi",
    saveChanges: "Tallenna muutokset",
    saved: "Tallennettu",
    changesSaved: "Ravintolan tiedot päivitetty.",
    qrCode: "QR-koodi",
    qrCodeDesc: "Asiakkaat skannaavat tämän avatakseen ruokalistan.",
    downloadQr: "Lataa PNG",
    copyLink: "Kopioi linkki",
    linkCopied: "Kopioitu!",
    filterSliders: "Asiakkaan suodattimet",
    filterSlidersDesc: "Aseta min/max-arvot, joita asiakkaat voivat säätää. Piilota liukusäädin kytkemällä se pois päältä.",
    sliderCalories: "Kalorit (kcal)",
    sliderProtein: "Proteiini (g)",
    sliderBudget: "Budjetti (€)",
    sliderMin: "Min",
    sliderMax: "Max",
    sliderEnabled: "Näytä liukusäädin",

    // Dashboard
    viewMenu: "Näytä ruokalista →",
    setupTitle: "Määritä ravintolasi",
    setupDesc: "Anna ravintolallesi nimi aloittaaksesi digitaalisen ruokalistan.",
    menuAvailableAt: "Ruokalistasi on saatavilla osoitteessa:",
    creating: "Luodaan...",
    createRestaurant: "Luo ravintola",
    restaurantBranding: "Ravintolan brändi",
    logo: "Logo",
    logoRecommended: "Suositeltu: 400 × 400 px · Neliö",
    logoFormats: "PNG, JPG tai HEIC",
    logoMaxSize: "Maks. 2 Mt",
    logoSizeError: "Logon on oltava alle 2 Mt.",
    coverPhoto: "Kansikuva",
    uploadCover: "Klikkaa ladataksesi kansikuvan",
    changeCover: "Vaihda kansikuva",
    coverRecommended: "Suositeltu: 1200 × 400 px",
    coverFormats: "PNG, JPG tai HEIC · Maks. 5 Mt",
    coverMaxSize: "Maks. 5 Mt",
    coverSizeError: "Kansikuvan on oltava alle 5 Mt.",
    pasteHint: "Liitä kuva (⌘V)",
    bannerBlur: "Kansikuvan sumennos",
    bannerBlurDesc: "Sumentele kansikuvaa niin, että ravintolan nimi pysyy luettavana.",
    categories: "Kategoriat",
    newCategory: "Uusi kategoria",
    menuItems: "Ruokalistan tuotteet",
    addItem: "Lisää tuote",
    editItem: "Muokkaa tuotetta",
    addMenuItem: "Lisää ruokalistan tuote",
    noItemsYet: "Ei tuotteita vielä. Lisää ensimmäinen!",
    uncategorized: "Luokittelematon",
    loadingMenu: "Ladataan ruokalistaa...",

    // Menu Item Form
    name: "Nimi",
    description: "Kuvaus",
    price: "Hinta",
    category: "Kategoria",
    selectCategory: "Valitse kategoria",
    calories: "Kalorit",
    proteinG: "Proteiini (g)",
    photo: "Kuva",
    currentPhoto: "Nykyinen kuva",
    changePhoto: "Vaihda kuva",
    removePhoto: "Poista kuva",
    photoWillBeRemoved: "Kuva poistetaan tallennettaessa.",
    undo: "Kumoa",
    allergens: "Allergeenit",
    dietaryTags: "Ruokavaliot",
    available: "Saatavilla",
    availability: "Saatavuus",
    alwaysAvailable: "Aina saatavilla",
    timeBased: "Aikarajoitettu",
    availableAt: "Saatavilla",
    addSlot: "Lisää aikajakso",
    slotFrom: "Alkaen",
    slotTo: "Asti",
    presetBreakfast: "Aamiainen",
    presetLunch: "Lounas",
    presetDinner: "Illallinen",
    notAvailableNow: "Ei saatavilla juuri nyt",
    saving: "Tallennetaan...",
    update: "Päivitä",
    cancel: "Peruuta",

    // Customer menu
    menuNotFound: "Ruokalistaa ei löydy",
    restaurantNotExist: "Tätä ravintolaa ei ole olemassa.",
    noMatchFilters: "Yksikään tuote ei vastaa suodattimiasi.",
    noMenuItems: "Ei ruokalistan tuotteita vielä.",
    discoverMore: "Tutustu muihin Tapli-ravintoloihin",
    filters: "Suodattimet",
    clear: "Tyhjennä",
    excludeAllergens: "Sulje pois allergeenit",
    dietaryPreference: "Ruokavalio",
    caloriesRange: "Kalorit",
    kcal: "kcal",
    protein: "proteiini",

    // Food style chips
    highProtein: "Proteiinipitoinen",
    highCarb: "Hiilihydraattipitoinen",
    highFatKeto: "Rasvapitoinen / Keto",
    lowCalorie: "Vähäkalorinen",
    highEnergy: "Energiapitoinen",
    plantBased: "Kasvispohjainen",

    // Roles
    owner: "Omistaja",
    generalManager: "Ravintolapäällikkö",
    headChef: "Keittiömestari",
    sousChef: "Vuorokokki",
    floorManager: "Salinjohtaja",
    marketingManager: "Markkinointipäällikkö",
    operationsManager: "Toimintapäällikkö",
    other: "Muu",

    // Pricing & Upgrade
    pricing: "Hinnoittelu",
    pricingTitle: "Yksinkertainen, läpinäkyvä hinnoittelu",
    pricingSubtitle: "Valitse ravintolaasi sopiva paketti. Vaihda tai peruuta milloin tahansa.",
    freeTrialNote: "Kaikki paketit sisältävät 14 päivän ilmaisen kokeilujakson. Luottokorttia ei tarvita.",
    planMonthly: "Kuukausittain",
    planQuarterly: "Neljännesvuosittain",
    planAnnual: "Vuosittain",
    perMonth: "/kk",
    billedMonthly: "Laskutetaan kuukausittain",
    billedQuarterly: "Laskutetaan 87 € joka 3. kuukausi",
    billedAnnually: "Laskutetaan 300 € vuodessa",
    save17: "Säästä 17 %",
    save29: "Säästä 29 %",
    mostPopular: "Suosituin",
    startFreeTrial: "Aloita ilmainen kokeilu",
    subscribeNow: "Tilaa nyt",
    upgradeTitle: "Päivitä pakettisi",
    upgradeSubtitle: "Valitse paketti jatkaaksesi Taplin käyttöä keskeytyksettä.",
    // Monthly features
    feat1Menu: "1 ruokalista",
    feat50Items: "Enintään 50 tuotetta",
    featQrNfc: "QR- ja NFC-tuki",
    featAllergenInfo: "Allergeeni- ja ruokavaliotiedot",
    featPhotoUploads: "Kuvien lataus",
    featBilingual: "Suomi- ja englanninkielinen tuki",
    featRealtimeUpdates: "Reaaliaikaiset päivitykset",
    featCustomColours: "Mukautetut ruokalistan värit",
    // Quarterly extra features
    feat3Menus: "Enintään 3 ruokalistaa",
    featUnlimitedItems: "Rajattomasti tuotteita",
    featItemBadges: "Tuotebadget (Uusi, Kokin suosikki)",
    featAnalytics: "Analytiikka ja katselukerrat",
    featPdfExport: "PDF-ruokalistan vienti",
    featPrioritySupport: "Prioriteettituki",
    // Annual extra features
    featExtraLanguages: "Lisäkielet (ruotsi, viro, venäjä)",
    featUnlimitedMenus: "Rajattomasti ruokalistoja",
    featTimedMenus: "Aikaperusteiset ruokalistat (lounas/illallinen)",
    featCustomQr: "Mukautettu QR-koodi ravintolan logolla",
    featOnboarding: "Käyttöönottosoitto",
    featAccountManager: "Oma asiakasvastaava",

    // Contact page
    contact: "Ota yhteyttä",
    contactTitle: "Ota yhteyttä",
    contactSubtitle: "Onko sinulla kysyttävää tai haluatko tehdä yhteistyötä? Ota yhteyttä milloin tahansa.",
    contactEmail: "Lähetä sähköpostia",
    contactFollowUs: "Seuraa meitä",

    // 404 page
    pageNotFound: "Sivua ei löydy",
    pageNotFoundDesc: "Hups! Etsimääsi sivua ei ole olemassa.",
    returnHome: "Palaa etusivulle",

    // Accessibility alt text
    logoAlt: "Ravintolan logo",
    coverAlt: "Ravintolan kansikuva",

    // Category name translations (English DB names → Finnish display name)
    catOffers: "Tarjoukset",
    catAppetizers: "Alkupalat",
    catSaladSoup: "Salaatti & Keitto",
    catPastaRisotto: "Pasta & Risotto",
    catPizzaLasagne: "Pizza & Lasagne",
    catForKids: "Lapsille",
    catVegan: "Vegaani",
    catDesserts: "Jälkiruoat",
    catDrinks: "Juomat",
    catAlcohol: "Alkoholi",
    catStarters: "Alkupalat",
    catMainCourses: "Pääruoat",
    catSideDishes: "Lisäkkeet",
    catAlcoholicDrinks: "Alkoholijuomat",
    catNonAlcoholicDrinks: "Alkoholittomat juomat",

    // Menu item form section headers
    freeFrom: "Ei sisällä",
    dietaryAndLifestyle: "Ruokavalio ja elämäntapa",
    optional: "valinnainen",
    englishTranslation: "Englanninkielinen käännös",
    translateToEn: "Käännä englanniksi",
    translateToFi: "Käännä suomeksi",
    translating: "Käännetään…",
    translateError: "Käännös epäonnistui",

    // Free From allergen tags — "vapaa ainesosista" style Finnish
    tagGlutenFree: "Gluteeniton",
    tagDairyFree: "Maidoton",
    tagEggFree: "Kananmunaton",
    tagFishFree: "Kalaton",
    tagPeanutFree: "Maapähkinätön",
    tagNutFree: "Pähkinätön",
    tagSoyFree: "Soijaton",
    tagShellfishFree: "Äyriäistön",
    tagSesameFree: "Seesaminsiemenetön",
    tagCeleryFree: "Selleritön",
    tagMustardFree: "Sinappiton",
    tagSulphiteFree: "Sulfiititon",
    tagLupinFree: "Lupiiniton",
    tagMolluscrFree: "Nilviäistön",

    // Dietary & lifestyle tags
    tagVegan: "Vegaaninen",
    tagVegetarian: "Kasvisruoka",
    tagLactoseFree: "Laktoositon",
    tagPlantBased: "Kasvipohjainen",
    tagLowCarb: "Vähähiilihydraattinen",
    tagKeto: "Keto",
    tagHighProtein: "Runsasproteiininen",
    tagNoAddedSugar: "Ei lisättyä sokeria",
    tagLowCalorie: "Vähäkalorinen",
    tagHalal: "Halal",
    tagKosher: "Kosher",
    tagNoPork: "Ei sianlihaa",
    tagNoAlcohol: "Ei alkoholia",
    tagNoBeef: "Ei naudanlihaa",
  },
} as const;

type TranslationKey = keyof typeof translations.en;

// Maps English DB category names to their translation key
const CATEGORY_KEY_MAP: Record<string, TranslationKey> = {
  "Offers": "catOffers",
  "Appetizers": "catAppetizers",
  "Salad & Soup": "catSaladSoup",
  "Pasta & Risotto": "catPastaRisotto",
  "Pizza & Lasagne": "catPizzaLasagne",
  "For Kids": "catForKids",
  "Vegan": "catVegan",
  "Desserts": "catDesserts",
  "Drinks": "catDrinks",
  "Alcohol": "catAlcohol",
  "Starters": "catStarters",
  "Main Courses": "catMainCourses",
  "Side Dishes": "catSideDishes",
  "Alcoholic Drinks": "catAlcoholicDrinks",
  "Non-Alcoholic Drinks": "catNonAlcoholicDrinks",
};

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  tCategory: (name: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
  tCategory: (name) => name,
});

export function useLanguage() {
  return useContext(LanguageContext);
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("tapli-lang") as Language) || "en";
    }
    return "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("tapli-lang", lang);
  };

  const t = (key: TranslationKey): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  // Translates a category name stored in the DB (always Finnish) to the current language
  const tCategory = (name: string): string => {
    const key = CATEGORY_KEY_MAP[name];
    return key ? t(key) : name;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tCategory }}>
      {children}
    </LanguageContext.Provider>
  );
}